from __future__ import annotations

from io import BytesIO, StringIO

import pytest

from options_income_engine.holdings import HoldingsCsvError, parse_holdings_csv
from options_income_engine.models import Holding


def test_parse_clean_simple_holdings_csv() -> None:
    csv = StringIO(
        "Symbol,Quantity,Cost Basis,Account\n"
        "TQQQ,200,8500.00,Merrill\n"
        "NVDA,125,14250.00,Merrill\n"
    )

    assert parse_holdings_csv(csv) == [
        Holding(ticker="TQQQ", shares=200, cost_basis=8500.0, account="Merrill"),
        Holding(ticker="NVDA", shares=125, cost_basis=14250.0, account="Merrill"),
    ]


def test_parse_merrill_style_csv_with_preamble_rows_before_header() -> None:
    csv = StringIO(
        "Merrill Lynch\n"
        "Account Holdings Export\n"
        "Account Number,1234\n"
        "As of,2026-07-09\n"
        "Security Symbol,Security Name,Qty,Last Price,Market Value,Total Cost Basis,Account Name\n"
        "AMD,Advanced Micro Devices,100,155.00,15500.00,15200.00,Brokerage\n"
        "GOOG,Alphabet,80,188.00,15040.00,11200.00,Brokerage\n"
    )

    assert parse_holdings_csv(csv) == [
        Holding(ticker="AMD", shares=100, cost_basis=15200.0, account="Brokerage"),
        Holding(ticker="GOOG", shares=80, cost_basis=11200.0, account="Brokerage"),
    ]


def test_parse_real_merrill_header_with_quoted_symbol_trailing_space() -> None:
    csv = StringIO(
        '"All Accounts","Value","Day\'s Value Change $","Unrealized Gain/Loss $ Chg % Chg"\n'
        '"Brokerage","$125,000.00","$100.00","$12,000.00 10.60%"\n'
        "\n"
        '"Symbol ","Value","Quantity","Price","Day\'s Price $ Chg % Chg","Day\'s Value Change $","Unrealized Gain/Loss $ Chg % Chg","Description"\n'
        '"TQQQ","$16,800.00","200","$84.00","$1.00 1.20%","$200.00","$8,300.00 97.65%","ProShares UltraPro QQQ"\n'
        '"NVDA","$20,500.00","125","$164.00","($2.00) -1.20%","($250.00)","$6,250.00 43.85%","NVIDIA Corp"\n'
        "\n"
        '"All Accounts","Value","Day\'s Value Change $","Unrealized Gain/Loss $ Chg % Chg"\n'
        '"Retirement","$50,000.00","$0.00","$5,000.00 11.10%"\n'
    )

    assert parse_holdings_csv(csv) == [
        Holding(ticker="TQQQ", shares=200, cost_basis=None, account=None),
        Holding(ticker="NVDA", shares=125, cost_basis=None, account=None),
    ]


def test_parse_csv_with_blank_rows_before_header() -> None:
    csv = StringIO(
        "\n\n"
        "Generated by Merrill\n"
        "\n"
        "Symbol,Description,Shares,Price\n"
        "MU,Micron,300,132.00\n"
    )

    assert parse_holdings_csv(csv) == [
        Holding(ticker="MU", shares=300, cost_basis=None, account=None),
    ]


def test_parse_alternate_ticker_and_shares_column_names() -> None:
    csv = BytesIO(
        b"Some disclaimer with no delimiter\n"
        b"Ticker,Security Name,Shares,Current Price\n"
        b"RKLB,Rocket Lab,250,28.00\n"
    )

    assert parse_holdings_csv(csv) == [
        Holding(ticker="RKLB", shares=250, cost_basis=None, account=None),
    ]


def test_malformed_file_raises_friendly_error_with_preview() -> None:
    csv = StringIO(
        "This is not a holdings export\n"
        "Account metadata only\n"
        "No useful table here\n"
    )

    with pytest.raises(HoldingsCsvError) as exc_info:
        parse_holdings_csv(csv)

    message = str(exc_info.value)
    assert "The uploaded file does not look like a holdings CSV." in message
    assert "Please export holdings with Symbol and Quantity/Shares columns." in message
    assert "First 20 lines:" in message
    assert "This is not a holdings export" in message
